import actions from './actiontypes';

export const getUser = () => {
    return (dispatch) => {
        const userData = [
            {"id": 1, "name": "Herbert", "email": "hstuffins0@washingtonpost.com"},
            {"id": 2, "name": "Lon", "email": "lchellenham1@clickbank.net"},
            {"id": 3, "name": "Persis", "email": "pdollen2@qq.com"},
            {"id": 4, "name": "Raquel", "email": "rgyrgorcewicx3@uiuc.edu"},
            {"id": 5, "name": "Deerdre", "email": "dgresswell4@sphinn.com"},
            {"id": 6, "name": "Diane", "email": "dthome5@webs.com"},
            {"id": 7, "name": "Francisco", "email": "frasmus6@blogs.com"},
            {"id": 8, "name": "Weider", "email": "wgouldbourn7@posterous.com"},
            {"id": 9, "name": "Callean", "email": "clebbern8@barnesandnoble.com"},
            {"id": 10, "name": "Christos", "email": "cmartinet9@shinystat.com"},
            {"id": 11, "name": "Ev", "email": "elittlera@webs.com"},
            {"id": 12, "name": "Nikolia", "email": "nmattiazzib@nymag.com"},
            {"id": 13, "name": "Alix", "email": "abonnorc@dmoz.org"},
            {"id": 14, "name": "Bamby", "email": "bjohanssend@tmall.com"},
            {"id": 15, "name": "Herold", "email": "hscusee@trellian.com"},
            {"id": 16, "name": "Averil", "email": "acallendarf@wired.com"},
            {"id": 17, "name": "Germana", "email": "gvaughtong@delicious.com"},
            {"id": 18, "name": "Corinna", "email": "celiasenh@blogtalkradio.com"},
            {"id": 19, "name": "Iolande", "email": "ivercruyssei@webnode.com"},
            {"id": 20, "name": "Layney", "email": "lconninghamj@slashdot.org"},
            {"id": 21, "name": "Danell", "email": "dgoomesk@irs.gov"},
            {"id": 22, "name": "Geordie", "email": "gbrittol@yandex.ru"},
            {"id": 23, "name": "Kelcie", "email": "ksewallm@businesswire.com"},
            {"id": 24, "name": "Ramon", "email": "rcoonann@mtv.com"},
            {"id": 25, "name": "Vanessa", "email": "vmccromleyo@smh.com.au"},
            {"id": 26, "name": "Germaine", "email": "grushfordp@twitpic.com"},
            {"id": 27, "name": "Ola", "email": "oparsandq@newyorker.com"},
            {"id": 28, "name": "Raina", "email": "rdoulr@behance.net"},
            {"id": 29, "name": "Adelaide", "email": "alaidlows@soundcloud.com"},
            {"id": 30, "name": "Donny", "email": "dcorneliussent@statcounter.com"},
            {"id": 31, "name": "Dinah", "email": "dtremblayu@theguardian.com"},
            {"id": 32, "name": "Holly", "email": "hkochsv@plala.or.jp"},
            {"id": 33, "name": "Lyle", "email": "lfodenw@plala.or.jp"},
            {"id": 34, "name": "Shir", "email": "sbettisonx@dagondesign.com"},
            {"id": 35, "name": "Court", "email": "cstairy@mac.com"},
            {"id": 36, "name": "Fairlie", "email": "fringrosez@com.com"},
            {"id": 37, "name": "Charlena", "email": "cpietrusiak10@lulu.com"},
            {"id": 38, "name": "Rosy", "email": "rharlow11@cafepress.com"},
            {"id": 39, "name": "Kore", "email": "ktombleson12@ezinearticles.com"},
            {"id": 40, "name": "Burr", "email": "binchboard13@weather.com"},
            {"id": 41, "name": "Orrin", "email": "omoohan14@amazon.co.uk"},
            {"id": 42, "name": "Tadio", "email": "tmarwood15@uol.com.br"},
            {"id": 43, "name": "Ardys", "email": "aduffin16@imdb.com"},
            {"id": 44, "name": "Heindrick", "email": "hgaspar17@last.fm"},
            {"id": 45, "name": "Christie", "email": "ckilcoyne18@ftc.gov"},
            {"id": 46, "name": "Tammara", "email": "tralph19@jimdo.com"},
            {"id": 47, "name": "Annis", "email": "agantzer1a@symantec.com"},
            {"id": 48, "name": "Mayer", "email": "meyes1b@reuters.com"},
            {"id": 49, "name": "Esme", "email": "ewyldish1c@pbs.org"},
            {"id": 50, "name": "Burnard", "email": "bfaye1d@behance.net"},
            {"id": 51, "name": "Virgilio", "email": "vgiampietro1e@addtoany.com"},
            {"id": 52, "name": "Randie", "email": "rgoosnell1f@nbcnews.com"},
            {"id": 53, "name": "Gavin", "email": "gpettwood1g@newyorker.com"},
            {"id": 54, "name": "Durant", "email": "dmcallister1h@ocn.ne.jp"},
            {"id": 55, "name": "Gottfried", "email": "gabthorpe1i@altervista.org"},
            {"id": 56, "name": "Udell", "email": "upapes1j@comcast.net"},
            {"id": 57, "name": "Riannon", "email": "rkiddle1k@tiny.cc"},
            {"id": 58, "name": "Osborn", "email": "ohaskins1l@so-net.ne.jp"},
            {"id": 59, "name": "Patrica", "email": "pnealey1m@bloglovin.com"},
            {"id": 60, "name": "Trescha", "email": "ttremberth1n@macromedia.com"},
            {"id": 61, "name": "Adina", "email": "aboosey1o@163.com"},
            {"id": 62, "name": "Towny", "email": "tfaichnie1p@liveinternet.ru"},
            {"id": 63, "name": "Belicia", "email": "bcarwithan1q@google.it"},
            {"id": 64, "name": "Moselle", "email": "mmossbee1r@icq.com"},
            {"id": 65, "name": "Clyve", "email": "cgogarty1s@paginegialle.it"},
            {"id": 66, "name": "Raquela", "email": "rkettle1t@yale.edu"},
            {"id": 67, "name": "Jolee", "email": "jgrishanov1u@virginia.edu"},
            {"id": 68, "name": "Stu", "email": "slabrow1v@simplemachines.org"},
            {"id": 69, "name": "Astrix", "email": "aquarmby1w@washington.edu"},
            {"id": 70, "name": "Lorelle", "email": "lgealle1x@youtube.com"},
            {"id": 71, "name": "Rainer", "email": "ranglin1y@europa.eu"},
            {"id": 72, "name": "Danella", "email": "dbrobak1z@mozilla.org"},
            {"id": 73, "name": "Margaux", "email": "mreuss20@mac.com"},
            {"id": 74, "name": "Alameda", "email": "acroson21@cornell.edu"},
            {"id": 75, "name": "Wendeline", "email": "wnoakes22@nature.com"},
            {"id": 76, "name": "Gordy", "email": "gdellorto23@ted.com"},
            {"id": 77, "name": "Beatrice", "email": "bbuckell24@baidu.com"},
            {"id": 78, "name": "Essa", "email": "eryan25@businesswire.com"},
            {"id": 79, "name": "Car", "email": "cpippard26@si.edu"},
            {"id": 80, "name": "Claudius", "email": "clawman27@bloglines.com"},
            {"id": 81, "name": "Cecily", "email": "chush28@wiley.com"},
            {"id": 82, "name": "Ave", "email": "akembley29@nih.gov"},
            {"id": 83, "name": "Seumas", "email": "sdurban2a@google.es"},
            {"id": 84, "name": "Puff", "email": "plillee2b@spotify.com"},
            {"id": 85, "name": "Bruce", "email": "bwhysall2c@nbcnews.com"},
            {"id": 86, "name": "Bari", "email": "blarver2d@feedburner.com"},
            {"id": 87, "name": "Delainey", "email": "drittmeier2e@etsy.com"},
            {"id": 88, "name": "Norbert", "email": "nlode2f@hexun.com"},
            {"id": 89, "name": "Merle", "email": "mnajara2g@umich.edu"},
            {"id": 90, "name": "Ashbey", "email": "amanchester2h@g.co"},
            {"id": 91, "name": "Pattie", "email": "pfarran2i@state.tx.us"},
            {"id": 92, "name": "Zea", "email": "zgiacobazzi2j@amazon.de"},
            {"id": 93, "name": "Colette", "email": "cczajka2k@fema.gov"},
            {"id": 94, "name": "Maud", "email": "mbaselli2l@blog.com"},
            {"id": 95, "name": "Linn", "email": "lhulburt2m@drupal.org"},
            {"id": 96, "name": "Horten", "email": "hfaulconbridge2n@bizjournals.com"},
            {"id": 97, "name": "Moyra", "email": "myakunin2o@spiegel.de"},
            {"id": 98, "name": "Myca", "email": "mdibdin2p@networkadvertising.org"},
            {"id": 99, "name": "Aryn", "email": "agaggen2q@un.org"},
            {"id": 100, "name": "Elsy", "email": "eduffrie2r@artisteer.com"}];
        dispatch({
            type: actions.GET_USER,
            payload: userData
        });
    }
};

